[package]
name = "voting-circuit"
version = "0.1.0"
type = "bin"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
std = { git = "https://github.com/noir-lang/noir", tag = "v0.28.0" }

